CWMT/CWMT/Controllers/ClassroomController.cs
using CWMasterTeacherDataModel;
using System;
using System.Web.Mvc;
using CWMasterTeacherService.ViewObjectBuilder;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherDomain.DomainObjects;
using CWMasterTeacherService.CUDRouters;
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMT.ReturnModels;

namespace CWMasterTeacher3
{
    [Authorize]
    public class ClassroomController : BaseController
    {
        private UserDomainObjBuilder _userObjBuilder;
        private ClassroomCUDRouter _classroomCUDRouter;
        private ClassroomViewObjBuilder _viewObjBuilder;
        private StudentManagerViewObjBuilder _studentManagerViewObjBuilder;

        public ClassroomController(UserDomainObjBuilder userObjBuilder, ClassroomViewObjBuilder classroomViewObjBuilder,
                            ClassroomCUDRouter classroomCUDRouter, StudentManagerViewObjBuilder studentManagerViewObjBuilder) :base(userObjBuilder)
        {
            _userObjBuilder = userObjBuilder;
            _viewObjBuilder = classroomViewObjBuilder;
            _classroomCUDRouter = classroomCUDRouter;
            _studentManagerViewObjBuilder = studentManagerViewObjBuilder;
        }

        public ActionResult Index(Guid? selectedTermId = null, Guid? selectedClassMeetingId = null, DateTime? selectedDate = null, 
                    bool showAllDates = false, bool showReferenceDocs = false, bool doShowStudentManager = false, 
                    Guid? classSectionId = null, bool showAllTerms = false)
        {
            try
            {
                ClassroomViewObj viewObj = _viewObjBuilder.RetrieveClassroomViewObj(currentUserId: CurrentUserId,
                                                                             selectedTermId: selectedTermId ?? Guid.Empty,
                                                                             selectedClassMeetingId: selectedClassMeetingId ?? Guid.Empty,
                                                                             showAllDates: showAllDates,
                                                                             selectedDate: selectedDate,
                                                                             showReferenceDocs: showReferenceDocs,
                                                                             doShowStudentManager: doShowStudentManager,
                                                                             classSectionId: classSectionId == null ? Guid.Empty : classSectionId.Value,
                                                                             showAllTerms: showAllTerms );


                return View(viewObj);
            }
            catch (Exception e)
            {
                WebLogger.Log.ClassroomControllerIndexFailed(e);
                throw;
            }

        }

        public ActionResult ClassroomPlan(Guid? selectedClassMeetingId = null, bool isPreview = false)
        {
            try
            {
                ClassroomPlanViewObj viewObj = _viewObjBuilder.RetrieveClassroomPlanViewObj(selectedClassMeetingId ?? Guid.Empty, isPreview);
                return View(viewObj);
            }
            catch (Exception e)
            {
                WebLogger.Log.ClassroomPlanFailed(e);
                throw;
            }

        }

        public ActionResult ClassroomWrap(Guid? classSectionId = null, Guid? selectedClassMeetingId = null, int awaitingApprovalCount = -1, bool doAllowEditing = false)
        {
            ClassroomWrapViewObj viewObj = _viewObjBuilder.RetrieveClassroomWrapViewObj(selectedClassMeetingId: selectedClassMeetingId == null ? Guid.Empty : selectedClassMeetingId.Value,
                                                                                            classSectionId: classSectionId == null ? Guid.Empty : classSectionId.Value,
                                                                                            awaitingApprovalCount: awaitingApprovalCount < 0 ? 0 : awaitingApprovalCount,
                                                                                            doAllowEditing: doAllowEditing);
            return View(viewObj);
        }

        public ActionResult StudentManager(Guid? classSectionId = null, Guid? selectedClassMeetingId = null)
        {
            StudentManagerViewObj viewObj = _studentManagerViewObjBuilder.Retrieve(classSectionId: classSectionId == null ? Guid.Empty : classSectionId.Value,
                                                            selectedClassMeetingId: selectedClassMeetingId == null ? Guid.Empty : selectedClassMeetingId.Value );
            return View(viewObj);
        }

        public ActionResult UpdateClassSectionStudent(Guid classSectionStudentId, Guid selectedClassMeetingId, ClassSectionStudentReturnModel xStudentObj)
        {
            _classroomCUDRouter.UpdateClassSectionStudent(classSectionStudentId: classSectionStudentId, 
                                                            hasBeenApproved: xStudentObj.HasBeenApproved, hasBeenDenied: xStudentObj.HasBeenDenied);
            return RedirectToAction("Index", new {selectedClassMeetingId = selectedClassMeetingId, doShowStudentManager = true });
        }

        public ActionResult ReleaseDocument(Guid documentId, Guid lessonUseId, Guid selectedClassMeetingId)
        {
            _classroomCUDRouter.ReleaseDocument(documentId, lessonUseId);
            return RedirectToAction("Index", new { selectedClassMeetingId = selectedClassMeetingId });
        }

        public ActionResult ReleaseAllDocuments(Guid lessonUseId, Guid selectedClassMeetingId)
        {
            _classroomCUDRouter.ReleaseAllDocuments(lessonUseId);
            return RedirectToAction("Index", new { selectedClassMeetingId = selectedClassMeetingId });
        }

        public ActionResult UnReleaseDocument(Guid releasedDocumentId, Guid selectedClassMeetingId)
        {
            _classroomCUDRouter.UnReleaseDocument(releasedDocumentId);
            return RedirectToAction("Index", new { selectedClassMeetingId = selectedClassMeetingId });
        }

        public ActionResult UnReleaseAllDocuments(Guid lessonUseId, Guid selectedClassMeetingId)
        {
            _classroomCUDRouter.UnReleaseAllDocumentsForLessonUse(lessonUseId);
            return RedirectToAction("Index", new { selectedClassMeetingId = selectedClassMeetingId });
        }

        public ActionResult SaveNotesForStudents(string notesForStudents, Guid selectedClassMeetingId)
        {
            _classroomCUDRouter.SaveNotesForStudents(notesForStudents, selectedClassMeetingId);
            return RedirectToAction("Index", new { selectedClassMeetingId = selectedClassMeetingId });
        }

        public ActionResult PreviewClassroomPlan(Guid? selectedClassMeetingId, Guid selectedClassSectionId)
        {
            try
            {
                return RedirectToAction("Index", new
                {
                    selectedClassMeetingId = selectedClassMeetingId ?? Guid.Empty,
                    classSectionId = selectedClassSectionId,
                });
            }
            catch(Exception e)
            {
                WebLogger.Log.PreviewClassroomPlanFailed(e);
                throw;
            }
        }

        public ActionResult ClassroomDocuments(Guid? selectedClassMeetingId = null, bool showReferenceDocs = false)
        {
            try
            {
                ClassroomDocsMeetingViewObj viewObj = _viewObjBuilder.RetrieveClassroomDocsMeetingViewObj(selectedClassMeetingId ?? Guid.Empty, showReferenceDocs);
                return View(viewObj);
            }
            catch (Exception e)
            {
                WebLogger.Log.ClassroomDocumentsFailed(e);
                throw;
            }

        }


        public ActionResult SetClassMeetingIsReady(ClassMeetingDomainObjBasic xMeeting, ClassroomReturnModel model)
        {
            try
            {
                _classroomCUDRouter.SetClassMeetingIsReady(xMeeting.Id, xMeeting.IsReadyToTeach);
                return RedirectToAction("Index", new
                {
                    selectedTermId = model.SelectedTermId,
                    selectedClassMeetingId = model.SelectedClassMeetingId,
                    selectedDate = model.SelectedDate,
                    showAllDates = model.ShowAllDates,
                    showReferenceDocs = model.ShowReferenceDocs
                });
            }
            catch (Exception e)
            {
                WebLogger.Log.SetClassMeetingIsReadyFailed(e);
                throw;
            }

        }

        public ActionResult MoveLessonForward(Guid selectedClassMeetingId, Guid selectedLessonUseId)
        {
            _classroomCUDRouter.MoveLessonForward(selectedLessonUseId);
            return RedirectToAction("Index", new { selectedClassMeetingId = selectedClassMeetingId });
        }

        public ActionResult CopyLessonForward(Guid selectedClassMeetingId, Guid selectedLessonUseId)
        {
            _classroomCUDRouter.CopyLessonForward(selectedLessonUseId);
            return RedirectToAction("Index", new { selectedClassMeetingId = selectedClassMeetingId });
        }

    }//End Class
}

CWMT/CWMT/Controllers/TextEditorController.cs
using CWMasterTeacherDataModel;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherService.ViewObjectBuilder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMasterTeacherDomain;

namespace CWMasterTeacher3
{
    [Authorize]
    public class TextEditorController : BaseController
    {
        NarrativeRepo _narrativeRepo;
        TextEditorViewObjBuilder _viewObjBuilder;

        public TextEditorController(NarrativeRepo narrativeRepo, UserDomainObjBuilder userObjBuilder, TextEditorViewObjBuilder textEditorViewObjBuilder) : base(userObjBuilder)
        {
            _narrativeRepo = narrativeRepo;
            _viewObjBuilder = textEditorViewObjBuilder;
        }
        
        public ActionResult Index(string editType, Guid objectId, Guid lessonId,  
                                    int lessonUseSequenceNumber = -1, bool isFromClassroomWrap = false, Guid? selectedClassMeetingId = null)
        {
            try
            {
                if (editType == DomainWebUtilities.TextEditType.Narrative )
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForNarrative(lessonId, CurrentUserId);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.LessonPlan)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForLessonPlan(objectId, lessonId, CurrentUserId);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.Message)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForMessage(parentMessageUseId: objectId, 
                                                                                           selectedLessonId: lessonId, 
                                                                                           currentUserId: CurrentUserId, 
                                                                                           isToSelf: false, 
                                                                                           isToStorage: false,
                                                                                           isFromClassroomWrap: isFromClassroomWrap );
                    return View(viewObj);
                }

                else if (editType == DomainWebUtilities.TextEditType.MessageToSelf )
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForMessage(parentMessageUseId: objectId,
                                                                                           selectedLessonId: lessonId,
                                                                                           currentUserId: CurrentUserId,
                                                                                           isToSelf: true,
                                                                                           isToStorage: false,
                                                                                           isFromClassroomWrap: isFromClassroomWrap);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.MessageToSelfStorage)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForMessage(parentMessageUseId: objectId,
                                                                                           selectedLessonId: lessonId,
                                                                                           currentUserId: CurrentUserId,
                                                                                           isToSelf: true,
                                                                                           isToStorage: true,
                                                                                           isFromClassroomWrap: isFromClassroomWrap);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.CustomLessonPlan)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForCustomLessonPlan(lessonUseId: objectId, 
                                                                    selectedLessonId: lessonId, 
                                                                    currentUserId: CurrentUserId,
                                                                    selectedClassMeetingId: selectedClassMeetingId == null ? Guid.Empty : selectedClassMeetingId.Value);
                    return View(viewObj);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                WebLogger.Log.TextEditorIndexFailed(e);
                throw;
            }


        }

    }
}

CWMT/CWMT/Views/Classroom/ClassroomDocuments.cshtml
@model CWMasterTeacherDomain.ViewObjects.ClassroomDocsMeetingViewObj

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>LessonPlan</title>

</head>
<body>

    <div class="cw-h4 cw-space-above-bigskip">@Model.Heading</div>

    @foreach (var xLesson in Model.DocsLessonList)
    {
        <div class=" cw-h5">
            @Html.DisplayFor(m => xLesson.LessonName)
        </div>
        
        <ul class=" cw-nobullet ">
            <li>Teaching Documents</li>
                <ul>
                    @foreach (var xDoc in xLesson.TeachingDocs)
                    {
                        <li>
                            <a href="@Url.Action("DownloadDocument", "Curriculum", new
                        {
                            documentUseId = xDoc.DocumentUseId,
                            isForEdit = false,
                            downloadPdfCopy = true,
                            skipSave = true
                        })" class=" cw-link " ,
                               target="_blank">
                                @xDoc.ExtendedDisplayName
                            </a>
                        </li>
                    }
                </ul>
            @if (xLesson.InstructorOnlyDocs.Count > 0)
            {
            <li>Instructor Only Documents</li>
            <ul>
                @foreach (var xDoc in xLesson.InstructorOnlyDocs)
                {
                    <li>
                        <a href="@Url.Action("DownloadDocument", "Curriculum", new
                            {
                                documentUseId = xDoc.DocumentUseId,
                                isForEdit = false,
                                downloadPdfCopy = true,
                                skipSave = true
                            })" class=" cw-link " ,
                           target="_blank">
                            @xDoc.DocumentName
                        </a>
                    </li>
                }

            </ul>
            }<!--End if-->
            @if (xLesson.ReferenceDocs.Count > 0)
            {
            <li>Reference Documents</li>
            <ul>
                @foreach (var xDoc in xLesson.ReferenceDocs)
                {
                    <li>
                        <a href="@Url.Action("DownloadDocument", "Curriculum", new
                            {
                                documentUseId = xDoc.DocumentUseId,
                                isForEdit = false,
                                downloadPdfCopy = true,
                                skipSave = true
                            })" class=" cw-link " ,
                           target="_blank">
                            @xDoc.DocumentName
                        </a>
                    </li>
                }
            </ul>
            }<!--End if-->


        </ul><!--End List for each lesson-->


    }<!--End foreach-->


</body>
</html>

CWMT/CWMT/Views/Classroom/ClassroomWrap.cshtml
@model CWMasterTeacherDomain.ViewObjects.ClassroomWrapViewObj

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClassroomWrap</title>
    <!-- Bootstrap core CSS -->
    <link href="Content/bootstrap.css" rel="stylesheet">
    <script src="Scripts/bootstrap.min.js" type="text/javascript"></script>

</head>
<body>
    <div class=" container-fluid ">
        <div class=" row">

            <div class=" col-md-9">
                @if (Model.AwaitingApprovalCount > 0)
                {
                    @Html.ActionLink(Model.AwaitingApprovalMessage, "Index", "Classroom",
                       routeValues: new { doShowStudentManager = true, classSectionId = Model.ClassSectionId },
                       htmlAttributes: new { @class = "cw-underline cw-red-bold" })
                }
            </div>
            <div class="col-md-3">
                @Html.ActionLink("Open Student Manager", "Index", "Classroom",
                       routeValues: new { doShowStudentManager = true, classSectionId = Model.ClassSectionId },
                       htmlAttributes: new { @class = "cw-underline" })

            </div>

        </div><!-- end row-->

        <div class=" row cw-h4 cw-border-bottom cw-space-below ">
            @Model.DateString
        </div>
        @using (Html.BeginForm("SaveNotesForStudents", "Classroom"))
            {
            <div class=" row cw-border-bottom cw-space-below">
                <div class=" col-md-3">
                    <div class="cw-bold pull-right">
                        Notes for Students
                    </div>
                    <div class=" cw-space-above-bigbigskip pull-right ">
                        <input type="submit" value="Submit Notes" />
                    </div>
                </div>

                <div class=" col-md-7">
                    @Html.TextAreaFor( model => model.NotesForStudents, new { style = " height: 120px;" })
                </div>
            </div>


            @Html.HiddenFor(m => m.SelectedClassMeetingId )
        }<!--End Form-->


        @foreach (var xLesson in Model.DocsLessonList)
        {
            <div class="row cw-h5">
                <div class=" col-md-6">
                    <div class="cw-title">
                        @xLesson.LessonName
                    </div>
                </div>
                <div class=" col-md-6">

                    <div class="btn-group">
                        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-option-horizontal"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Post Message", "Index", "TextEditor",
                                routeValues: new
                                {
                                    objectId = Guid.Empty,
                                    lessonId = xLesson.LessonId,
                                    editType = Model.MessageEditType,
                                    isFromClassroomWrap = true
                                },
                                htmlAttributes: new { @class = "" })
                            </li>
                            <li>
                                @Html.ActionLink("Note to Self", "Index", "TextEditor",
                                routeValues: new
                                {
                                    objectId = Guid.Empty,
                                    lessonId = xLesson.LessonId,
                                    editType = Model.NoteToSelfEditType,
                                    isFromClassroomWrap = true
                                },
                                htmlAttributes: new { @class = " " })
                            </li>
                            <li>
                                @Html.ActionLink("Move Lesson to Next Class", "MoveLessonForward", "Classroom",
                                routeValues: new
                                {
                                    selectedLessonUseId = xLesson.LessonUseId,
                                    selectedClassMeetingId = Model.SelectedClassMeetingId
                                },
                                htmlAttributes: new { @class = " " })
                            </li>
                            <li>
                                @Html.ActionLink("Copy Lesson to Next Class", "CopyLessonForward", "Classroom",
                                routeValues: new
                                {
                                    selectedLessonUseId = xLesson.LessonUseId,
                                    selectedClassMeetingId = Model.SelectedClassMeetingId
                                },
                                htmlAttributes: new { @class = " " })
                            </li>
                        </ul>
                    </div><!--End button group-->


                </div><!--End column-->


            </div>
            <div class=" row cw-border-bottom">

                <div class=" col-md-6">
                    <ul class=" cw-nobullet ">


                        @if (xLesson.UnreleasedTeachingDocs != null && xLesson.UnreleasedTeachingDocs.Count > 0)
                {
                            <li>Teaching Documents</li>
                            <ul>
                                @foreach (var xDoc in xLesson.UnreleasedTeachingDocs)
                                {
                                    <li>
                                        <a href="@Url.Action("ReleaseDocument", "Classroom", new
                            {
                                documentId = xDoc.DocumentId,
                                lessonUseId = xLesson.LessonUseId,
                                selectedClassMeetingId = Model.SelectedClassMeetingId
                            })" class=" cw-link ">
                                            @xDoc.DocumentName
                                        </a>
                                    </li>
                                }

                            </ul>
                        }<!--End if-->

                        @if (xLesson.UnreleasedReferenceDocs != null && xLesson.UnreleasedReferenceDocs.Count > 0 && Model.DoShowReferenceDocs)
                        {
                            <li>Reference Documents</li>
                            <ul>
                                @foreach (var xDoc in xLesson.UnreleasedReferenceDocs)
                                {
                                    <li>
                                        <a href="@Url.Action("ReleaseDocument", "Classroom", new
                            {
                                documentId = xDoc.DocumentId,
                                lessonUseId = xLesson.LessonUseId,
                                selectedClassMeetingId = Model.SelectedClassMeetingId
                            })" class=" cw-link ">
                                            @xDoc.DocumentName
                                        </a>
                                    </li>
                                }
                            </ul>
                        }<!--End if-->


                    </ul><!--End List for each lesson-->
                </div>
                <div class=" col-md-1">

                    <div class="row cw-space-above-bigskip  ">
                        @Html.ActionLink(">>>", "ReleaseAllDocuments", "Classroom",
                        routeValues: new
                        {
                            lessonUseId = xLesson.LessonUseId,
                            selectedClassMeetingId = Model.SelectedClassMeetingId
                        },
                        htmlAttributes: new { @class = "cw-h4 " })
                    </div>

                    <div class="row cw-space-above  ">
                        @Html.ActionLink("<<<", "UnReleaseAllDocuments", "Classroom",
                        routeValues: new
                        {
                            lessonUseId = xLesson.LessonUseId,
                            selectedClassMeetingId = Model.SelectedClassMeetingId
                        },
                        htmlAttributes: new { @class = "cw-h4 " })
                    </div>

                </div><!--End Column-->
                <div class=" col-md-5">
                    <ul class=" cw-nobullet ">
                        @if (xLesson.ReleasedDocs != null && xLesson.ReleasedDocs.Count > 0)
                {
                            <li>Released Documents</li>
                            <ul>
                                @foreach (var xDoc in xLesson.ReleasedDocs)
                                {
                                    <li>
                                        <a href="@Url.Action("UnReleaseDocument", "Classroom", new
                            {
                                        releasedDocumentId = xDoc.Id,
                                        selectedClassMeetingId = Model.SelectedClassMeetingId
                            })" class=" cw-link ">
                                            @xDoc.DocumentObj.Name
                                        </a>
                                    </li>
                                }

                            </ul>
                        }<!--End if-->

                    </ul>
                </div>

            </div>




        }<!--End foreach-->



    </div>
</body>
</html>

CWMT/CWMT/Views/Classroom/StudentManager.cshtml
@model CWMasterTeacherDomain.ViewObjects.StudentManagerViewObj
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StudentManager</title>
</head>
<body>
    <div class=" container-fluid ">
        <div class=" row">
            <div class="cw-h4 col-md-8 cw-space-above">
                Student Manager
            </div>
            <div class="col-md-4 cw-space-above">
                @Html.ActionLink("Done", "Index", "Classroom",
                        routeValues: new
                        {

                        },
                        htmlAttributes: new { @class = "cw-underline cw-button-md " })

            </div>

        </div>

        @helper ListStudents(List<CWMasterTeacherDomain.DomainObjects.ClassSectionStudentDomainObjBasic> studentObjs)
        {

        foreach (var xStudentObj in studentObjs)
        {
            <div class=" row cw-border-bottom ">
                <div class=" col-md-4">
                    @Html.DisplayFor(m => xStudentObj.StudentFullName, new { @class = " cw-space-above" })
                </div>
                <div class=" col-md-3">
                    @using (Html.BeginForm("UpdateClassSectionStudent", "Classroom", routeValues: new { classSectionStudentId = xStudentObj.Id }))
                    {
                        @Html.CheckBoxFor(m => xStudentObj.HasBeenApproved, htmlAttributes: new { onchange = "this.form.submit();" })
                        @Html.LabelFor(m => xStudentObj.HasBeenApproved, new { @class = " cw-checkbox-label" })
                        @Html.HiddenFor(m => Model.ClassSectionId)
                        @Html.HiddenFor(m => xStudentObj.HasBeenDenied)
                        @Html.HiddenFor(m => m.SelectedClassMeetingId)
                    }<!--End form-->
                </div>
                <div class=" col-md-5">
                    @using (Html.BeginForm("UpdateClassSectionStudent", "Classroom", routeValues: new { classSectionStudentId = xStudentObj.Id }))
                    {
                        @Html.CheckBoxFor(m => xStudentObj.HasBeenDenied, htmlAttributes: new { onchange = "this.form.submit();" })
                        @Html.LabelFor(m => xStudentObj.HasBeenDenied, new { @class = " cw-checkbox-label" })
                        @Html.HiddenFor(m => Model.ClassSectionId)
                        @Html.HiddenFor(m => xStudentObj.HasBeenApproved)
                        @Html.HiddenFor(m => m.SelectedClassMeetingId)
                    }<!--End form-->

                </div>

            </div>
        }

}      <!--End Helper-->

        @if (Model.DoShowWaitingForApproval)
        {
            <div class=" row">
                <div class=" cw-h5">Students Waiting for Approval </div>
            </div>
            <div class=" row">
                @ListStudents(Model.StudentsWaitingForApproval)
            </div>
        }

        @if (Model.DoShowDeniedStudents)
        {
            <div class=" row">
                <div class=" cw-h5">Students Who Have Been Denied </div>
            </div>
            <div class=" row">
                @ListStudents(Model.StudentsDenied)
            </div>
        }

        @if (Model.DoShowCurrentStudents)
        {
            <div class=" row">
                <div class=" cw-h5">Current Students </div>
            </div>
            <div class=" row">
                @ListStudents(Model.CurrentStudents)
            </div>
        }



    </div>

</body>
</html>