CWMT/CWMT/Controllers/CurriculumController.cs
using CWMasterTeacherDataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.IO;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Configuration;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherService.ViewObjectBuilder;
using Ninject;
using CWMasterTeacherService;
using CWMasterTeacherDomain;
using CWMasterTeacherService.CUDServices;
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMasterTeacherDomain.DomainObjects;
using CWMasterTeacherService.CUDRouters;

namespace CWMasterTeacher3
{
    [Authorize]
    public class CurriculumController : BaseController
    {

        private UserDomainObjBuilder _userObjBuilder;
        private DocumentStorageService _documentStorageService;
        private MessageBoardViewObjBuilder _messageBoardViewObjBuilder;
        private CurriculumViewObjBuilder _curriculumViewObjBuilder;
        private DocumentsTabViewObjBuilder _documentsTabViewObjBuilder;
        private LessonPlanViewObjBuilder _lessonPlanViewObjBuilder;
        private NarrativeViewObjBuilder _narrativeViewObjBuilder;
        private LessonDomainObjBuilder _lessonObjBuilder;
        private MessageUseDomainObjBuilder _messageUseObjBuilder;
        private DocumentDomainObjBuilder _documentObjBuilder;

        private CurriculumCUDRouter _curriculumCUDRouter;
        private NarrativeTabCUDRouter _narrativeTabCUDRouter;
        private LessonPlanTabCUDRouter _lessonPlanTabCUDRouter;
        private MessageBoardTabCUDRouter _messageBoardTabCUDRouter;
        private DocumentsTabCUDRouter _documentsTabCUDRouter;

        public CurriculumController(UserDomainObjBuilder userObjBuilder,  
                DocumentStorageService documentStorageService,
                MessageBoardViewObjBuilder messageBoardViewObjBuilder, 
                DocumentsTabViewObjBuilder documentsTabViewObjBuilder, CurriculumViewObjBuilder curriculumViewObjBuilder,
                LessonPlanViewObjBuilder lessonPlanViewObjBuilder, NarrativeViewObjBuilder narrativeViewObjBuilder,
                LessonDomainObjBuilder lessonObjBuilder, MessageUseDomainObjBuilder messageUseObjBuilder,
                DocumentDomainObjBuilder documentObjBuilder, CurriculumCUDRouter curriculumCUDRouter,
                NarrativeTabCUDRouter narrativeTabCUDRouter, LessonPlanTabCUDRouter lessonPlanTabCUDRouter,
                MessageBoardTabCUDRouter messageBoardTabCUDRouter, DocumentsTabCUDRouter documentsTabCUDRouter)

            : base(userObjBuilder)
        {
            _userObjBuilder = userObjBuilder;
            _documentStorageService = documentStorageService;
            _documentsTabViewObjBuilder = documentsTabViewObjBuilder;
            _messageBoardViewObjBuilder = messageBoardViewObjBuilder;
            _curriculumViewObjBuilder = curriculumViewObjBuilder;
            _lessonPlanViewObjBuilder = lessonPlanViewObjBuilder;
            _narrativeViewObjBuilder = narrativeViewObjBuilder;

            _documentObjBuilder = documentObjBuilder;
            _lessonObjBuilder = lessonObjBuilder;
            _messageUseObjBuilder = messageUseObjBuilder;

            _curriculumCUDRouter = curriculumCUDRouter;
            _narrativeTabCUDRouter = narrativeTabCUDRouter;
            _lessonPlanTabCUDRouter = lessonPlanTabCUDRouter;
            _messageBoardTabCUDRouter = messageBoardTabCUDRouter;
            _documentsTabCUDRouter = documentsTabCUDRouter;

        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="courseId">Only relevant when a Lesson has not been selected. Otherwise will default to Course containing Lesson</param>
        /// <param name="lessonId">If Lesson is selected</param>
        /// <param name="showMasters">Show master courses in dropdown</param>
        /// <param name="showAll">Show all courses in dropdown</param>
        /// <param name="displayMessageUseId">Pass to Message Board</param>
        /// <param name="showArchivedMessages">Pass to Message Board</param>
        /// <param name="selectedDocumentUseId">Pass to Documents Tab</param>
        /// <param name="selectedDocumentId">Pass to Documents Tab</param>
        /// <param name="showUploadDialog">Pass to Documents Tab</param>
        /// <param name="showArchivedDocs">Pass to Documents Tab</param>
        /// <param name="showThisManyDocs">Pass to Documents Tab</param>
        /// <param name="isPdfCopyUpload">Pass to Documents Tab</param>
        /// <param name="fileValidationMessage">Pass to Documents Tab</param>
        /// <param name="showGroupLessons">Pass to Group Tab</param>
        /// <param name="showGroupNarrative">Pass to Group Tab</param>
        /// <param name="showGroupLessonPlan">Pass to Group Tab</param>
        /// <param name="showGroupDocuments">Pass to Group Tab</param>
        /// <param name="groupSelectedLessonId">Pass to Group Tab</param>
        /// <param name="groupReferenceLessonId">Pass to Group Tab</param>
        /// <param name="groupSelectedDocumentUseId">Pass to Group Tab</param>
        /// <param name="showGroupTab">Pass to Group Tab</param>
        /// <param name="showGroupDocStorage">Pass to Group Tab</param>
        /// <returns></returns>

        public ActionResult Index(Guid? courseId = null, Guid? lessonId = null, bool showMasters = false,
                                bool showAll = false, Guid? displayMessageUseId = null, bool showArchivedMessages = false,
                                Guid? selectedDocumentUseId = null, Guid? selectedDocumentId = null, bool showUploadDialog = false,
                                bool showArchivedDocs = false, int showThisManyDocs = -1, bool isPdfCopyUpload = false,
                                string fileValidationMessage = "", bool showGroupLessons = false, bool showGroupNarrative = false, 
                                bool showGroupLessonPlan = false, bool showGroupDocuments = false, Guid? groupSelectedLessonId = null, Guid? groupReferenceLessonId = null,
                                Guid? groupSelectedDocumentUseId = null, bool showGroupTab = false, bool showGroupDocStorage = false)
        {

            try
            {
                //I have been told that best practice is that all optional integers have the same default value, I'm using -1 as the default.  Hence the following code
                if (showThisManyDocs < 0)
                {
                    showThisManyDocs = 10;
                }

                Guid lastDisplayedCourseId = CurrentUserObj.LastDisplayedCourseId;


                CurriculumViewObj viewObj = _curriculumViewObjBuilder.RetrieveCurriculumViewObj(currentUserName: CurrentUserName, 
                                                                                        courseId: courseId ?? Guid.Empty, 
                                                                                        lessonId: lessonId ?? Guid.Empty, 
                                                                                        showMasters: showMasters, 
                                                                                        showAll: showAll, 
                                                                                        displayMessageUseId: displayMessageUseId ?? Guid.Empty,
                                                                                        showArchivedMessages: showArchivedMessages,
                                                                                        selectedDocumentUseId: selectedDocumentUseId ?? Guid.Empty,
                                                                                        selectedDocumentId: selectedDocumentId ?? Guid.Empty,
                                                                                        showUploadDialog: showUploadDialog,
                                                                                        showArchivedDocs: showArchivedDocs,
                                                                                        showThisManyDocs: showThisManyDocs,
                                                                                        isPdfCopyUpload: isPdfCopyUpload,
                                                                                        fileValidationMessage: fileValidationMessage,
                                                                                        showGroupDocStorage: showGroupDocStorage);



                //ViewData["ComboAction"] = "CoursesAll";
                //ViewData["ComboController"] = "CourseInfo";
                ModelState.Clear();
                return View(viewObj);
            }
            catch (Exception e)
            {
                WebLogger.Log.CurriculumIndexFailed(e);
                throw;
            }
        }

        public ActionResult SetCourseListDisplayValues(bool showMasters = false, bool showAll = false, Guid? selectedLessonId = null)
        {

            _curriculumCUDRouter.SetCourseListDisplayValues(currentUserId: CurrentUserId, showMasters: showMasters, showAll: showAll);

            return RedirectToAction("Index", new {lessonId = selectedLessonId ?? Guid.Empty });
        }

        /// <summary>
        /// Toggles whether we are editing an individual Lesson or master Lesson.  Should only available to those with Master Edit credentials
        /// </summary>
        /// <param name="isMasterEdit"></param>
        /// <param name="selectedLessonId"></param>
        /// <param name="returnLessonId">Id of individual Lesson to return to</param>
        /// <returns></returns>
        public ActionResult ToggleMasterEdit(bool isMasterEdit, Guid selectedLessonId, Guid returnLessonId)
        {
            try
            {

CWMT/CWMT/Controllers/StudentHomeController.cs
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherService.CUDRouters;
using CWMasterTeacherService.DomainObjectBuilders;
using CWMasterTeacherService.ViewObjectBuilder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CWMT.Controllers
{
    public class StudentHomeController : BaseStudentController
    {
        private StudentHomeViewObjBuilder _studentHomeViewObjBuilder;
        private StudentHomeCUDRouter _studentHomeCUDRouter;

        public StudentHomeController(UserDomainObjBuilder userObjBuilder, StudentUserDomainObjBuilder studentUserObjBuilder,
                        StudentHomeCUDRouter studentHomeCUDRouter, StudentHomeViewObjBuilder studentHomeViewObjBuilder)
                        :base(userObjBuilder, studentUserObjBuilder)
        {
            _studentHomeCUDRouter = studentHomeCUDRouter;
            _studentHomeViewObjBuilder = studentHomeViewObjBuilder;
        }
        // GET: StudentHome
        public ActionResult Index(Guid? workingGroupId = null, Guid? termId = null, 
                                    Guid? instructorUserId = null, Guid? classSectionId = null, 
                                    bool doShowRequestCourseAccess = false, string accessRequestMessage = "",
                                    bool doShowRequestGroupAccess = false, Guid? selectedInstructorId = null,
                                    string courseRequestMessage = "", Guid? displayedClassSectionId = null,
                                    Guid? selectedClassMeetingId = null, bool showAllDates = false)
        {
            StudentHomeViewObj viewObj = _studentHomeViewObjBuilder.Retrieve(studentUserObj: CurrentStudentUserObj,
                                                                                instructorUserId: instructorUserId == null ? Guid.Empty : instructorUserId.Value,
                                                                                classSectionId: classSectionId == null ? Guid.Empty : classSectionId.Value,
                                                                                doShowRequestCourseAccess: doShowRequestCourseAccess,
                                                                                accessRequestMessage: accessRequestMessage,
                                                                                doShowRequestGroupAccess: doShowRequestGroupAccess,
                                                                                courseRequestMessage: courseRequestMessage,
                                                                                displayedClassSectionId: displayedClassSectionId == null ? Guid.Empty : displayedClassSectionId.Value,
                                                                                selectedClassMeetingId: selectedClassMeetingId == null ? Guid.Empty : selectedClassMeetingId.Value,
                                                                                doShowAllDates: showAllDates );
            return View(viewObj);
        }

        public ActionResult RequestGroupAccess(string accessCode)
        {
            string message = _studentHomeCUDRouter.RequestGroupAccessReturnMessage(CurrentStudentUserId, accessCode);

            return RedirectToAction("Index", new { accessRequestMessage = message });
        }

        public ActionResult RequestCourseAccess(Guid classSectionId)
        {
            string message = _studentHomeCUDRouter.RequestCourseAccessReturnMessage(CurrentStudentUserId, classSectionId);
            return RedirectToAction("Index", new { courseRequestMessage = message });
        }

    }
}

CWMT/CWMT/Views/StudentHome/Index.cshtml
@model CWMasterTeacherDomain.ViewObjects.StudentHomeViewObj
@{
    Layout = "~/Views/Shared/_LayoutCWStudent.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <!-- Bootstrap core CSS -->
    <link href="Content/bootstrap.css" rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class=" container-fluid">
        <div class=" row">
            <div class="col-md-3 ">
                <div class=" row">
                    <div class="btn-group pull-right">
                        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Request Access <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Request Group Access", "Index", "StudentHome",
                                    routeValues: new
                                    {
                                        doShowRequestGroupAccess = true
                                    },
                                    htmlAttributes: new {})

                            </li>
                            <li>
                                @if (!Model.DoShowRequestCourseAccess)
                                {

                                    @Html.ActionLink("Request Course Access", "Index", "StudentHome", new { doShowRequestCourseAccess = true }, new { })

                                }

                            </li>

                        </ul>
                    </div><!--End Button Group-->


                </div>
                <div class=" row">
                    <div class=" cw-bold cw-space-above">
                        @Model.WelcomeMessage
                    </div>

                    @if (Model.DoShowGroupAccessInstructions)
                    {
                        <div class=" cw-red-bold cw-space-above-bigbigskip">
                            @Model.GroupAccessInstructions
                        </div>
                    }

                    @if (Model.WorkingGroupList != null && Model.WorkingGroupList.Count > 0)
                    {
                        <div class=" cw-bold cw-space-above-bigskip">
                            Groups:
                        </div>
                    }

                </div>
                @foreach (var xGroup in Model.WorkingGroupList)
                {
                    <div>
                        @Html.DisplayFor(x => xGroup.Name);
                    </div>
                }

                <div class=" row">


                </div>
                @if (Model.DoShowRequestGroupAccess)
                {
                    using (Html.BeginForm("RequestGroupAccess", "StudentHome"))
                    {
                        <div class=" row cw-space-above-bigbigskip">
                            @Html.LabelFor(model => model.AccessCode, htmlAttributes: new { @class = "control-label " })
                            @Html.TextBoxFor(model => model.AccessCode, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class=" row cw-space-above-bigskip">
                            <div class=" col-md-6">
                                <input type="submit" value="Submit Access Code" class="cw-button-md" />
                            </div>


                            <div class=" col-md-6">
                                @Html.ActionLink("Cancel", "Index", "StudentHome", null, new { @class = "cw-button-md" })
                            </div>

                            @Html.HiddenFor(m => Model.DoShowRequestCourseAccess)
                        </div><!-- End Row-->
                    }<!--End form-->
                }<!--End if(doShowRequestGroupAccess)-->

                <div class=" row">
                    <div class=" cw-red-bold cw-space-above-bigskip ">
                        @Html.DisplayFor(m => Model.AccessRequestMessage)
                    </div>
                </div>
                @if (Model.DoShowCourseAccessInstructions)
                {
                <div class=" cw-red-bold cw-space-above-bigskip">
                    @Model.CourseAccessInstructions
                </div>
                }

                @if (Model.DoShowRequestCourseAccess)
                {
                    <div class=" cw-space-above-bigbigskip">
                        @using (Html.BeginForm("Index", "StudentHome"))
                        {
                            <div>
                                @Html.LabelFor(model => model.InstructorUserId, htmlAttributes: new { @class = "control-label " })
                            </div>
                            <div>
                                @Html.DropDownListFor(m => Model.InstructorUserId, Model.InstructorSelectList, "Select Instructor", new { onchange = "this.form.submit();" })
                            </div>
                            @Html.HiddenFor(m => Model.DoShowRequestCourseAccess)
                        }
                    </div>

                    <div class=" cw-space-above-bigskip">
                        @using (Html.BeginForm("Index", "StudentHome"))
                        {
                            <div>
                                @Html.LabelFor(model => model.ClassSectionId, htmlAttributes: new { @class = "control-label " })
                            </div>
                            <div>
                                @Html.DropDownListFor(m => Model.ClassSectionId, Model.ClassSectionSelectList, "Select ClassSection", new { onchange = "this.form.submit();" })
                            </div>
                            @Html.HiddenFor(m => Model.DoShowRequestCourseAccess)
                            @Html.HiddenFor(m => Model.InstructorUserId)
                        }
                    </div>

                    <div class="cw-space-above-bigskip">
                        <div class=" row">
                            <div class="col-md-8">
                                @using (Html.BeginForm("RequestCourseAccess", "StudentHome"))
                                {
                                    if (Model.ClassSectionId != Guid.Empty)
                                    {
                                        <input type="submit" value="Submit Request" class="cw-button-md" />
                                    }
                                    @Html.HiddenFor(m => Model.ClassSectionId)
                                }
                                @if (Model.ClassSectionId == Guid.Empty)
                                {
                                    <div class=" cw-bold">
                                        Select Instructor and Class Section
                                    </div>
                                }
                            </div>

                            <div class=" col-md-4">
                                @Html.ActionLink("Cancel", "Index", "StudentHome", null, new { @class = "cw-button-md" })
                            </div>
                        </div>
                    </div>
                }<!--End if (DoShowRequestCourseAccess)-->

                <div class=" row cw-space-above-bigskip">
                    <div class=" cw-red-bold ">
                        @Html.DisplayFor(m => Model.CourseRequestMessage)
                    </div>
                </div>

                @if (Model.DoShowWaitingForApprovalList)
                {
                    <div class=" cw-bold cw-space-above">
                        Courses Waiting for Approval:
                    </div>
                    foreach (CWMasterTeacherDomain.DomainObjects.ClassSectionStudentDomainObjBasic xSection in Model.ClassesAwaitingApprovalClassSecStdt)
                    {
                        <div>
                            @Html.DisplayFor(x => xSection.ClassSectionName)
                        </div>
                    }
                }

                @if (Model.DoShowDeniedList)
                {
                    <div class=" cw-bold cw-space-above">
                        Request for access was denied for these class sections.  Please speak with your instructor.
                    </div>
                    foreach (CWMasterTeacherDomain.DomainObjects.ClassSectionStudentDomainObjBasic xSection in Model.ClassesDeniedClassSecStdt)
                    {
                        <div>
                            @Html.DisplayFor(x => xSection.ClassSectionName)
                        </div>
                    }
                }

                @if (Model.DoShowCurrentClasses)
                {
                    <div class=" cw-bold cw-space-above-bigbigskip">
                        Current Classes:
                    </div>
                    foreach (var xSection in Model.CurrentClassesClassSecStdt)
                    {
                        <div>
                            @Html.ActionLink(xSection.ClassSectionName, "Index", "StudentHome",
                                            new { displayedClassSectionId = xSection.ClassSectionId, showAllDates = Model.ShowAllDates },
                                            new { @class = "cw-underline" })
                        </div>
                    }
                }




            </div><!--End column-->

            <div class="col-md-3 ">

                <div id="possibledates" class=" cw-border">
                    <div class=" row">
                        <div class=" pull-right cw-space-left-right">
                            @using (Html.BeginForm("Index", "StudentHome"))
                            {
                                <span>@Html.CheckBoxFor(m => Model.ShowAllDates, new { onchange = "this.form.submit();" })</span>
                                <span>Show All Dates</span>

                                @Html.HiddenFor(m => Model.DisplayedClassSectionId)
                            }
                        </div>
                        <div class=" cw-h5 cw-space-left-right">Select Date</div>

                    </div><!--End row-->

                    <div class=" cw-scroll-30">
                        <ul class=" cw-noindent ">
                            @foreach (var xMeeting in Model.ClassMeetingSelectionList)
                            {
                                <li>
                                    @Html.ActionLink(xMeeting.MeetingDateString, "Index", "StudentHome",
                                            new
                                            {
                                                selectedClassMeetingId = xMeeting.Id,
                                                showAllDates = Model.ShowAllDates,
                                                displayedClassSectionId = Model.DisplayedClassSectionId
                                            },
                                            new { @class = xMeeting.DisplayClass })
                                </li>
                            }
                        </ul>
                    </div><!--End scroll-->
                </div><!--End possible dates-->
            </div><!--End column-->


            <div class="col-md-6 ">
                <div class=" cw-h4 cw-space-below ">
                    @Model.SelectedMeetingDateString
                </div>
                @if (Model.SelectedClassMeetingObj != null)
                {
                    <div class=" cw-bold">Notes from Instructor</div>

                    <div class=" cw-lessonuse-border">
                        @Html.DisplayFor(model => model.NotesForStudents, new { style = " height: 120px" })
                    </div>
                }

                <div class=" cw-space-above-bigskip cw-h4">
                    Documents for Activities
                </div>


                <div class=" cw-space-above-bigskip"></div>

                @foreach (var xLesson in Model.LessonDisplayList)
                {

                    if (xLesson.ReleasedDocs != null && xLesson.ReleasedDocs.Count > 0)
                    {
                        <div class=" cw-h5">
                            @Html.DisplayFor(m => xLesson.LessonName)
                        </div>
                        <ul>
                            @foreach (var xDoc in xLesson.ReleasedDocs)
                            {
                                <li>
                                    <a href="@Url.Action("DownloadDocument", "Curriculum", new
                                                    {
                                                        documentId = xDoc.DocumentId,
                                                        isForEdit = false,
                                                        downloadPdfCopy = true,
                                                        skipSave = true
                                                    })" class=" cw-link " ,
                                       target="_blank">
                                        @xDoc.DocumentName
                                    </a>
                                </li>
                            }

                        </ul>
                    }<!--End if-->
                }<!--End foreach-->

            </div>


        </div><!--End Row-->
    </div><!--End Container Fluid-->
</body>
</html>