CWMT/CWMT/Controllers/CurriculumController.cs
using CWMasterTeacherDataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.IO;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Configuration;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherService.ViewObjectBuilder;
using Ninject;
using CWMasterTeacherService;
using CWMasterTeacherDomain;
using CWMasterTeacherService.CUDServices;
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMasterTeacherDomain.DomainObjects;
using CWMasterTeacherService.CUDRouters;

namespace CWMasterTeacher3
{
    [Authorize]
    public class CurriculumController : BaseController
    {

        private UserDomainObjBuilder _userObjBuilder;
        private DocumentStorageService _documentStorageService;
        private MessageBoardViewObjBuilder _messageBoardViewObjBuilder;
        private CurriculumViewObjBuilder _curriculumViewObjBuilder;
        private DocumentsTabViewObjBuilder _documentsTabViewObjBuilder;
        private LessonPlanViewObjBuilder _lessonPlanViewObjBuilder;
        private NarrativeViewObjBuilder _narrativeViewObjBuilder;
        private LessonDomainObjBuilder _lessonObjBuilder;
        private MessageUseDomainObjBuilder _messageUseObjBuilder;
        private DocumentDomainObjBuilder _documentObjBuilder;

        private CurriculumCUDRouter _curriculumCUDRouter;
        private NarrativeTabCUDRouter _narrativeTabCUDRouter;
        private LessonPlanTabCUDRouter _lessonPlanTabCUDRouter;
        private MessageBoardTabCUDRouter _messageBoardTabCUDRouter;
        private DocumentsTabCUDRouter _documentsTabCUDRouter;

        public CurriculumController(UserDomainObjBuilder userObjBuilder,  
                DocumentStorageService documentStorageService,
                MessageBoardViewObjBuilder messageBoardViewObjBuilder, 
                DocumentsTabViewObjBuilder documentsTabViewObjBuilder, CurriculumViewObjBuilder curriculumViewObjBuilder,
                LessonPlanViewObjBuilder lessonPlanViewObjBuilder, NarrativeViewObjBuilder narrativeViewObjBuilder,
                LessonDomainObjBuilder lessonObjBuilder, MessageUseDomainObjBuilder messageUseObjBuilder,
                DocumentDomainObjBuilder documentObjBuilder, CurriculumCUDRouter curriculumCUDRouter,
                NarrativeTabCUDRouter narrativeTabCUDRouter, LessonPlanTabCUDRouter lessonPlanTabCUDRouter,
                MessageBoardTabCUDRouter messageBoardTabCUDRouter, DocumentsTabCUDRouter documentsTabCUDRouter)

            : base(userObjBuilder)
        {
            _userObjBuilder = userObjBuilder;
            _documentStorageService = documentStorageService;
            _documentsTabViewObjBuilder = documentsTabViewObjBuilder;
            _messageBoardViewObjBuilder = messageBoardViewObjBuilder;
            _curriculumViewObjBuilder = curriculumViewObjBuilder;
            _lessonPlanViewObjBuilder = lessonPlanViewObjBuilder;
            _narrativeViewObjBuilder = narrativeViewObjBuilder;

            _documentObjBuilder = documentObjBuilder;
            _lessonObjBuilder = lessonObjBuilder;
            _messageUseObjBuilder = messageUseObjBuilder;

            _curriculumCUDRouter = curriculumCUDRouter;
            _narrativeTabCUDRouter = narrativeTabCUDRouter;
            _lessonPlanTabCUDRouter = lessonPlanTabCUDRouter;
            _messageBoardTabCUDRouter = messageBoardTabCUDRouter;
            _documentsTabCUDRouter = documentsTabCUDRouter;

        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="courseId">Only relevant when a Lesson has not been selected. Otherwise will default to Course containing Lesson</param>
        /// <param name="lessonId">If Lesson is selected</param>
        /// <param name="showMasters">Show master courses in dropdown</param>
        /// <param name="showAll">Show all courses in dropdown</param>
        /// <param name="displayMessageUseId">Pass to Message Board</param>
        /// <param name="showArchivedMessages">Pass to Message Board</param>
        /// <param name="selectedDocumentUseId">Pass to Documents Tab</param>
        /// <param name="selectedDocumentId">Pass to Documents Tab</param>
        /// <param name="showUploadDialog">Pass to Documents Tab</param>
        /// <param name="showArchivedDocs">Pass to Documents Tab</param>
        /// <param name="showThisManyDocs">Pass to Documents Tab</param>
        /// <param name="isPdfCopyUpload">Pass to Documents Tab</param>
        /// <param name="fileValidationMessage">Pass to Documents Tab</param>
        /// <param name="showGroupLessons">Pass to Group Tab</param>
        /// <param name="showGroupNarrative">Pass to Group Tab</param>
        /// <param name="showGroupLessonPlan">Pass to Group Tab</param>
        /// <param name="showGroupDocuments">Pass to Group Tab</param>
        /// <param name="groupSelectedLessonId">Pass to Group Tab</param>
        /// <param name="groupReferenceLessonId">Pass to Group Tab</param>
        /// <param name="groupSelectedDocumentUseId">Pass to Group Tab</param>
        /// <param name="showGroupTab">Pass to Group Tab</param>
        /// <param name="showGroupDocStorage">Pass to Group Tab</param>
        /// <returns></returns>

        public ActionResult Index(Guid? courseId = null, Guid? lessonId = null, bool showMasters = false,
                                bool showAll = false, Guid? displayMessageUseId = null, bool showArchivedMessages = false,
                                Guid? selectedDocumentUseId = null, Guid? selectedDocumentId = null, bool showUploadDialog = false,
                                bool showArchivedDocs = false, int showThisManyDocs = -1, bool isPdfCopyUpload = false,
                                string fileValidationMessage = "", bool showGroupLessons = false, bool showGroupNarrative = false, 
                                bool showGroupLessonPlan = false, bool showGroupDocuments = false, Guid? groupSelectedLessonId = null, Guid? groupReferenceLessonId = null,
                                Guid? groupSelectedDocumentUseId = null, bool showGroupTab = false, bool showGroupDocStorage = false)
        {

            try
            {
                //I have been told that best practice is that all optional integers have the same default value, I'm using -1 as the default.  Hence the following code
                if (showThisManyDocs < 0)
                {
                    showThisManyDocs = 10;
                }

                Guid lastDisplayedCourseId = CurrentUserObj.LastDisplayedCourseId;


                CurriculumViewObj viewObj = _curriculumViewObjBuilder.RetrieveCurriculumViewObj(currentUserName: CurrentUserName, 
                                                                                        courseId: courseId ?? Guid.Empty, 
                                                                                        lessonId: lessonId ?? Guid.Empty, 
                                                                                        showMasters: showMasters, 
                                                                                        showAll: showAll, 
                                                                                        displayMessageUseId: displayMessageUseId ?? Guid.Empty,
                                                                                        showArchivedMessages: showArchivedMessages,
                                                                                        selectedDocumentUseId: selectedDocumentUseId ?? Guid.Empty,
                                                                                        selectedDocumentId: selectedDocumentId ?? Guid.Empty,
                                                                                        showUploadDialog: showUploadDialog,
                                                                                        showArchivedDocs: showArchivedDocs,
                                                                                        showThisManyDocs: showThisManyDocs,
                                                                                        isPdfCopyUpload: isPdfCopyUpload,
                                                                                        fileValidationMessage: fileValidationMessage,
                                                                                        showGroupDocStorage: showGroupDocStorage);



                //ViewData["ComboAction"] = "CoursesAll";
                //ViewData["ComboController"] = "CourseInfo";
                ModelState.Clear();
                return View(viewObj);
            }
            catch (Exception e)
            {
                WebLogger.Log.CurriculumIndexFailed(e);
                throw;
            }
        }

        public ActionResult SetCourseListDisplayValues(bool showMasters = false, bool showAll = false, Guid? selectedLessonId = null)
        {

            _curriculumCUDRouter.SetCourseListDisplayValues(currentUserId: CurrentUserId, showMasters: showMasters, showAll: showAll);

            return RedirectToAction("Index", new {lessonId = selectedLessonId ?? Guid.Empty });
        }

        /// <summary>
        /// Toggles whether we are editing an individual Lesson or master Lesson.  Should only available to those with Master Edit credentials
        /// </summary>
        /// <param name="isMasterEdit"></param>
        /// <param name="selectedLessonId"></param>
        /// <param name="returnLessonId">Id of individual Lesson to return to</param>
        /// <returns></returns>
        public ActionResult ToggleMasterEdit(bool isMasterEdit, Guid selectedLessonId, Guid returnLessonId)
        {
            try
            {

CWMT/CWMT/Controllers/TextEditorController.cs
using CWMasterTeacherDataModel;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherService.ViewObjectBuilder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMasterTeacherDomain;

namespace CWMasterTeacher3
{
    [Authorize]
    public class TextEditorController : BaseController
    {
        NarrativeRepo _narrativeRepo;
        TextEditorViewObjBuilder _viewObjBuilder;

        public TextEditorController(NarrativeRepo narrativeRepo, UserDomainObjBuilder userObjBuilder, TextEditorViewObjBuilder textEditorViewObjBuilder) : base(userObjBuilder)
        {
            _narrativeRepo = narrativeRepo;
            _viewObjBuilder = textEditorViewObjBuilder;
        }
        
        public ActionResult Index(string editType, Guid objectId, Guid lessonId,  
                                    int lessonUseSequenceNumber = -1, bool isFromClassroomWrap = false, Guid? selectedClassMeetingId = null)
        {
            try
            {
                if (editType == DomainWebUtilities.TextEditType.Narrative )
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForNarrative(lessonId, CurrentUserId);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.LessonPlan)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForLessonPlan(objectId, lessonId, CurrentUserId);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.Message)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForMessage(parentMessageUseId: objectId, 
                                                                                           selectedLessonId: lessonId, 
                                                                                           currentUserId: CurrentUserId, 
                                                                                           isToSelf: false, 
                                                                                           isToStorage: false,
                                                                                           isFromClassroomWrap: isFromClassroomWrap );
                    return View(viewObj);
                }

                else if (editType == DomainWebUtilities.TextEditType.MessageToSelf )
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForMessage(parentMessageUseId: objectId,
                                                                                           selectedLessonId: lessonId,
                                                                                           currentUserId: CurrentUserId,
                                                                                           isToSelf: true,
                                                                                           isToStorage: false,
                                                                                           isFromClassroomWrap: isFromClassroomWrap);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.MessageToSelfStorage)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForMessage(parentMessageUseId: objectId,
                                                                                           selectedLessonId: lessonId,
                                                                                           currentUserId: CurrentUserId,
                                                                                           isToSelf: true,
                                                                                           isToStorage: true,
                                                                                           isFromClassroomWrap: isFromClassroomWrap);
                    return View(viewObj);
                }
                else if (editType == DomainWebUtilities.TextEditType.CustomLessonPlan)
                {
                    TextEditorViewObj viewObj = _viewObjBuilder.RetrieveViewObjForCustomLessonPlan(lessonUseId: objectId, 
                                                                    selectedLessonId: lessonId, 
                                                                    currentUserId: CurrentUserId,
                                                                    selectedClassMeetingId: selectedClassMeetingId == null ? Guid.Empty : selectedClassMeetingId.Value);
                    return View(viewObj);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                WebLogger.Log.TextEditorIndexFailed(e);
                throw;
            }


        }

    }
}

CWMT/CWMT/Views/Curriculum/GroupLessonPlan.cshtml
@model CWMasterTeacher3.GroupLessonPlanViewModel

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Group Class Notes</title>
</head>

<body>

    <div class="cw-h5">
        @Model.Heading
    </div>

    <div>
        @Html.TextAreaFor(model => Model.LessonPlanText, 0, 0, new { id = "groupLessonPlanDisplay", @class = "mceReadOnlySmall" })
    </div>


</body>

</html>

CWMT/CWMT/Views/Curriculum/GroupLessons.cshtml
@model CWMasterTeacher3.GroupLessonsViewModel

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Group Lessons</title>
</head>

<body>
    <div class="cw-h5">
        @Model.Heading 
    </div>

    <div>
        @if (Model.GroupLessonDisplayVMList != null && Model.GroupLessonDisplayVMList.Count > 0)
        {
            <ul>
                @foreach (var xLesson in Model.GroupLessonDisplayVMList)
                {
                <li>
                    @Html.ActionLink(xLesson.LessonName, "Index", "Curriculum",
                             routeValues: new
                             {
                                 groupReferenceLessonId = xLesson.LessonId,
                                 lessonId = Model.SelectedLessonId,
                                 showGroupTab = true
                             },
                        htmlAttributes: new { })
                </li>
                }
            </ul>

        }

    </div>


</body>

</html>

CWMT/CWMT/Views/Curriculum/GroupNarrative.cshtml
@model CWMasterTeacher3.GroupNarrativeViewModel

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Group Narrative</title>
</head>

<body>

    <div class="cw-h5 cw-space-below">
        @Model.Heading
    </div>

    <div>
        <div>
            @Html.TextAreaFor(model => Model.NarrativeText, 0, 0, new { id = "groupNarrativeDisplay", @class = "mceReadOnlySmall" })
        </div>
    </div>


</body>

</html>

CWMT/CWMT/Views/Curriculum/GroupTabInactive.cshtml
@model CWMasterTeacher3.GroupTabInactiveViewModel

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Group Tab</title>
</head>

<body>

    <div class="cw-space-above">
        @Html.ActionLink("Show Group Lessons", "Index", "Curriculum",
                            new { lessonId = Model.SelectedLessonId, showGroupTab = true },
                            new { @class = "cw-underline" })
    </div>




</body>
</html>

CWMT/CWMT/Views/Curriculum/LessonPlan.cshtml
@model CWMasterTeacherDomain.LessonPlanViewObj

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClassNotes</title>

</head>
<body>

    <div class="container-fluid ">
        <div class="row">
            <div class="col-md-4">
                @if (Model.SelectedLessonId != Guid.Empty && Model.HasBasicEditRights)
                {
                    @Html.ActionLink(Model.LessonPlanEditLinkText, "Index", "TextEditor", new
               {
                   editType = "LessonPlan",
                   objectId = Model.LessonPlanId,
                   lessonId = Model.SelectedLessonId
               }, new { @class = "cw-underline" })
                }

            </div>


            <div class="col-md-3">
                @if (Model.ShowComparisonLessonLink)
                {
                    @Html.ActionLink(@Model.ComparisonLessonLinkText, "ViewComparisonLessonsMode", "LessonCompare", new
               {
                   editableLessonId = Model.SelectedLessonId,
                   isDisplayModeLessonPlan = true
               },
                        new { @class = "cw-underline-blue" });
                }

            </div>

            <div class="col-md-3">
                @Model.DateLabelText
            </div>
            <div class="col-md-2">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-option-horizontal"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            @Html.ActionLink("Archive a copy", "StashLessonPlan", "Curriculum",
                                            routeValues: new
                                            {
                                                lessonId = Model.SelectedLessonId,
                                                lessonPlanId = Model.LessonPlanId
                                            },
                                            htmlAttributes: new { })
                        </li>
                        <li>
                            <a href="@Url.Action("ViewArchiveMode", "LessonCompare", new {
                                        editableLessonId = Model.SelectedLessonId,
                                        isDisplayModeLessonPlan = true
                                    })">View Archive</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("ViewComparisonLessonsMode", "LessonCompare", new {
                                        editableLessonId = Model.SelectedLessonId,
                                        isDisplayModeLessonPlan = true
                                    })">View Comparison Lessons</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("ViewImportContentMode", "LessonCompare", new {
                                        editableLessonId = Model.SelectedLessonId,
                                        isDisplayModeLessonPlan = true
                                    })">Import Content</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ViewImportLessonMode", "LessonCompare", new {
                                    editableLessonId = Model.SelectedLessonId,
                                    isDisplayModeLessonPlan = true
                                })">Import Lesson</a>
                        </li>

                        <li class=" divider"></li>
                        <li>
                            <a href="@Url.Action("ViewReviewChangesToIndividualMode", "LessonCompare", new {
                                                editableLessonId = Model.SelectedLessonId,
                                                isDisplayModeLessonPlan = true
                                                })">Review Group Changes</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ViewReviewChangesToMasterMode", "LessonCompare", new {
                                                editableLessonId = Model.SelectedLessonId,
                                                isDisplayModeLessonPlan = true
                                                })">Review Master Course Changes</a>
                        </li>

                    </ul>
                </div><!--End Button Group-->
            </div><!--End Column-->
        </div>
    </div>



    <div>
        @Html.TextAreaFor(model => Model.DisplayText, 0, 0, new { id = "lessonPlanEdit", @class = "mceReadOnly" })
    </div>



</body>
</html>

CWMT/CWMT/Views/Curriculum/MessageBoard.cshtml
@model CWMasterTeacherDomain.ViewObjects.MessageBoardViewObj

@{
    Layout = null;
}



<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>MessageBoard</title>
</head>

<body>




    <div class="container-fluid">
        @if (Model.SelectedLessonId != Guid.Empty)
        {
            <div class="row">
                <div class="col-md-8">
                    <div id="messageTree">

                        @helper ShowTree(IEnumerable<CWMasterTeacherDomain.DomainObjects.MessageUseDomainObj> messageUseModels)
{

                        <ul class="cw-noindent">
                            @foreach (var x in messageUseModels)
                            {
                                <li>

                                    @Html.ActionLink(x.DisplayName, "Index", "Curriculum",
                                                        new { displayMessageUseId = x.Id, lessonId = Model.SelectedLessonId, showArchivedMessages = Model.ShowArchived },
                                                         new { @class = x.DisplayClass })


                                    @if (x.ChildMessageUseObjList.Any())
                                    {
                                        @ShowTree(x.ChildMessageUseObjList)
                                    }
                                </li>
                            }
                        </ul>
}       @*end helper*@

<ul class="cw-noindent">
    <li class="cw-h5">Current Messages</li>
    @ShowTree(Model.LiveMessages)
</ul>

@if (Model.StoredMessages.Count > 0)
{
    <ul class="cw-noindent">
        <li class="cw-h5">Stored Messages</li>
        @ShowTree(Model.StoredMessages)
    </ul>
}

@if (Model.ShowArchived)
{
    <ul class="cw-noindent">
        <li class="cw-h5">Archived Messages</li>
        @ShowTree(Model.ArchivedMessages)
    </ul>
}

</div>  <!--end  id =messageTree-->
</div> <!--end col-md-10-->
<div class="col-md-4">
    <div class="btn-group">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Compose <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            @if (Model.DisplayMessageUseId != Guid.Empty)
            {
                <li><a href="@Url.Action("Index", "TextEditor", new { objectId = Model.DisplayMessageUseId, lessonId = Model.SelectedLessonId, editType = "Message"})">Reply</a></li>
            }
            <li><a href="@Url.Action("Index", "TextEditor", new { objectId = Guid.Empty, lessonId = Model.SelectedLessonId, editType = "Message" })">New Message</a></li>
            <li><a href="@Url.Action("Index", "TextEditor", new { objectId = Guid.Empty, lessonId = Model.SelectedLessonId, editType = "MessageToSelf" })">Note to Self</a></li>
            <li><a href="@Url.Action("Index", "TextEditor", new { objectId = Guid.Empty, lessonId = Model.SelectedLessonId, editType = "MessageToSelfStorage" })">Note to Self: To Storage</a></li>
        </ul>
    </div>

    <div class="btn-group">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Other Actions  <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            @if (Model.DisplayMessageUseId != Guid.Empty)
            {


                <li>
                    <a href="@Url.Action("UpdateMessageUseIsStored", "Curriculum", new
                                            {
                                                lessonId = Model.SelectedLessonId,
                                                messageUseId = Model.DisplayMessageUseId,
                                                isStored = !@Model.IsDisplayStored
                                            })">@Model.StoredMenuText</a>
                                        </li>

                                        <li>
                                            <a href="@Url.Action("UpdateMessageUseIsArchived", "Curriculum", new
                                                {
                                                    lessonId = Model.SelectedLessonId,
                                                    messageUseId = Model.DisplayMessageUseId,
                                                    isArchived = Model.IsDisplayArchived,
                                                    isShowArchived = Model.IsDisplay_IsShowArchived
                                            })">@Model.ArchivedMenuText</a>
                                        </li>

                                        <li>
                                            <a href="@Url.Action("UpdateMessageUseIsImportant", "Curriculum", new
                                            { lessonId = Model.SelectedLessonId,
                                                messageUseId = Model.DisplayMessageUseId,
                                                isImportant = !@Model.IsDisplayImportant
                                            })">@Model.ImportantMenuText</a>
                                        </li>

                                        <li>
                                            <a href="@Url.Action("UpdateMessageUseIsForEndOfSemRev", "Curriculum", new
                                            {
                                                lessonId = Model.SelectedLessonId,
                                                messageUseId = Model.DisplayMessageUseId,
                                                isForEndOfSemRev = !@Model.IsDisplayForEndOfSemRev
                                            })">@Model.EndOfSemRevMenuText</a>
                                        </li>

            }<!--End If (DisplayMessageUseId != Guid.Empty)-->
            <li class="divider"></li>
            @if (!Model.ShowArchived)
            {
                <li>
                    <a href="@Url.Action("Index", "Curriculum", new
                                            {
                                                lessonId = Model.SelectedLessonId, showArchivedMessages = true 
                                            })">Show Archived Messages</a>
                </li>
            }<!--End if(!Model.ShowArchived)-->
            @if (Model.ShowArchived)
            {
                <li>
                    <a href="@Url.Action("Index", "Curriculum", new
                                            {
                                                lessonId = Model.SelectedLessonId, showArchivedMessages = false 
                                            })">Hide Archived Messages</a>
                </li>
            }<!--End if(!Model.ShowArchived)-->
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("UpdateAllMessageBooleans", "Curriculum", new
                                            {
                                                lessonId = Model.SelectedLessonId,
                                            })">Update Message Icons</a>
            </li>

        </ul>
    </div>

</div><!--end col-md-2-->

</div> <!--end row-->
            <div>
                @Html.TextAreaFor(model => Model.DisplayMessageText, 0, 0, new { id = "messageDisplay", @class = "mceReadOnly" })
            </div>

        }<!--End If SelectedLessonId != Guid.Empty-->
    </div> <!--end container-fluid-->


</body>
</html>