CWMT/CWMT/Controllers/CurriculumController.cs
using CWMasterTeacherDataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.IO;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Configuration;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherService.ViewObjectBuilder;
using Ninject;
using CWMasterTeacherService;
using CWMasterTeacherDomain;
using CWMasterTeacherService.CUDServices;
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMasterTeacherDomain.DomainObjects;
using CWMasterTeacherService.CUDRouters;

namespace CWMasterTeacher3
{
    [Authorize]
    public class CurriculumController : BaseController
    {

        private UserDomainObjBuilder _userObjBuilder;
        private DocumentStorageService _documentStorageService;
        private MessageBoardViewObjBuilder _messageBoardViewObjBuilder;
        private CurriculumViewObjBuilder _curriculumViewObjBuilder;
        private DocumentsTabViewObjBuilder _documentsTabViewObjBuilder;
        private LessonPlanViewObjBuilder _lessonPlanViewObjBuilder;
        private NarrativeViewObjBuilder _narrativeViewObjBuilder;
        private LessonDomainObjBuilder _lessonObjBuilder;
        private MessageUseDomainObjBuilder _messageUseObjBuilder;
        private DocumentDomainObjBuilder _documentObjBuilder;

        private CurriculumCUDRouter _curriculumCUDRouter;
        private NarrativeTabCUDRouter _narrativeTabCUDRouter;
        private LessonPlanTabCUDRouter _lessonPlanTabCUDRouter;
        private MessageBoardTabCUDRouter _messageBoardTabCUDRouter;
        private DocumentsTabCUDRouter _documentsTabCUDRouter;

        public CurriculumController(UserDomainObjBuilder userObjBuilder,  
                DocumentStorageService documentStorageService,
                MessageBoardViewObjBuilder messageBoardViewObjBuilder, 
                DocumentsTabViewObjBuilder documentsTabViewObjBuilder, CurriculumViewObjBuilder curriculumViewObjBuilder,
                LessonPlanViewObjBuilder lessonPlanViewObjBuilder, NarrativeViewObjBuilder narrativeViewObjBuilder,
                LessonDomainObjBuilder lessonObjBuilder, MessageUseDomainObjBuilder messageUseObjBuilder,
                DocumentDomainObjBuilder documentObjBuilder, CurriculumCUDRouter curriculumCUDRouter,
                NarrativeTabCUDRouter narrativeTabCUDRouter, LessonPlanTabCUDRouter lessonPlanTabCUDRouter,
                MessageBoardTabCUDRouter messageBoardTabCUDRouter, DocumentsTabCUDRouter documentsTabCUDRouter)

            : base(userObjBuilder)
        {
            _userObjBuilder = userObjBuilder;
            _documentStorageService = documentStorageService;
            _documentsTabViewObjBuilder = documentsTabViewObjBuilder;
            _messageBoardViewObjBuilder = messageBoardViewObjBuilder;
            _curriculumViewObjBuilder = curriculumViewObjBuilder;
            _lessonPlanViewObjBuilder = lessonPlanViewObjBuilder;
            _narrativeViewObjBuilder = narrativeViewObjBuilder;

            _documentObjBuilder = documentObjBuilder;
            _lessonObjBuilder = lessonObjBuilder;
            _messageUseObjBuilder = messageUseObjBuilder;

            _curriculumCUDRouter = curriculumCUDRouter;
            _narrativeTabCUDRouter = narrativeTabCUDRouter;
            _lessonPlanTabCUDRouter = lessonPlanTabCUDRouter;
            _messageBoardTabCUDRouter = messageBoardTabCUDRouter;
            _documentsTabCUDRouter = documentsTabCUDRouter;

        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="courseId">Only relevant when a Lesson has not been selected. Otherwise will default to Course containing Lesson</param>
        /// <param name="lessonId">If Lesson is selected</param>
        /// <param name="showMasters">Show master courses in dropdown</param>
        /// <param name="showAll">Show all courses in dropdown</param>
        /// <param name="displayMessageUseId">Pass to Message Board</param>
        /// <param name="showArchivedMessages">Pass to Message Board</param>
        /// <param name="selectedDocumentUseId">Pass to Documents Tab</param>
        /// <param name="selectedDocumentId">Pass to Documents Tab</param>
        /// <param name="showUploadDialog">Pass to Documents Tab</param>
        /// <param name="showArchivedDocs">Pass to Documents Tab</param>
        /// <param name="showThisManyDocs">Pass to Documents Tab</param>
        /// <param name="isPdfCopyUpload">Pass to Documents Tab</param>
        /// <param name="fileValidationMessage">Pass to Documents Tab</param>
        /// <param name="showGroupLessons">Pass to Group Tab</param>
        /// <param name="showGroupNarrative">Pass to Group Tab</param>
        /// <param name="showGroupLessonPlan">Pass to Group Tab</param>
        /// <param name="showGroupDocuments">Pass to Group Tab</param>
        /// <param name="groupSelectedLessonId">Pass to Group Tab</param>
        /// <param name="groupReferenceLessonId">Pass to Group Tab</param>
        /// <param name="groupSelectedDocumentUseId">Pass to Group Tab</param>
        /// <param name="showGroupTab">Pass to Group Tab</param>
        /// <param name="showGroupDocStorage">Pass to Group Tab</param>
        /// <returns></returns>

        public ActionResult Index(Guid? courseId = null, Guid? lessonId = null, bool showMasters = false,
                                bool showAll = false, Guid? displayMessageUseId = null, bool showArchivedMessages = false,
                                Guid? selectedDocumentUseId = null, Guid? selectedDocumentId = null, bool showUploadDialog = false,
                                bool showArchivedDocs = false, int showThisManyDocs = -1, bool isPdfCopyUpload = false,
                                string fileValidationMessage = "", bool showGroupLessons = false, bool showGroupNarrative = false, 
                                bool showGroupLessonPlan = false, bool showGroupDocuments = false, Guid? groupSelectedLessonId = null, Guid? groupReferenceLessonId = null,
                                Guid? groupSelectedDocumentUseId = null, bool showGroupTab = false, bool showGroupDocStorage = false)
        {

            try
            {
                //I have been told that best practice is that all optional integers have the same default value, I'm using -1 as the default.  Hence the following code
                if (showThisManyDocs < 0)
                {
                    showThisManyDocs = 10;
                }

                Guid lastDisplayedCourseId = CurrentUserObj.LastDisplayedCourseId;


                CurriculumViewObj viewObj = _curriculumViewObjBuilder.RetrieveCurriculumViewObj(currentUserName: CurrentUserName, 
                                                                                        courseId: courseId ?? Guid.Empty, 
                                                                                        lessonId: lessonId ?? Guid.Empty, 
                                                                                        showMasters: showMasters, 
                                                                                        showAll: showAll, 
                                                                                        displayMessageUseId: displayMessageUseId ?? Guid.Empty,
                                                                                        showArchivedMessages: showArchivedMessages,
                                                                                        selectedDocumentUseId: selectedDocumentUseId ?? Guid.Empty,
                                                                                        selectedDocumentId: selectedDocumentId ?? Guid.Empty,
                                                                                        showUploadDialog: showUploadDialog,
                                                                                        showArchivedDocs: showArchivedDocs,
                                                                                        showThisManyDocs: showThisManyDocs,
                                                                                        isPdfCopyUpload: isPdfCopyUpload,
                                                                                        fileValidationMessage: fileValidationMessage,
                                                                                        showGroupDocStorage: showGroupDocStorage);



                //ViewData["ComboAction"] = "CoursesAll";
                //ViewData["ComboController"] = "CourseInfo";
                ModelState.Clear();
                return View(viewObj);
            }
            catch (Exception e)
            {
                WebLogger.Log.CurriculumIndexFailed(e);
                throw;
            }
        }

        public ActionResult SetCourseListDisplayValues(bool showMasters = false, bool showAll = false, Guid? selectedLessonId = null)
        {

            _curriculumCUDRouter.SetCourseListDisplayValues(currentUserId: CurrentUserId, showMasters: showMasters, showAll: showAll);

            return RedirectToAction("Index", new {lessonId = selectedLessonId ?? Guid.Empty });
        }

        /// <summary>
        /// Toggles whether we are editing an individual Lesson or master Lesson.  Should only available to those with Master Edit credentials
        /// </summary>
        /// <param name="isMasterEdit"></param>
        /// <param name="selectedLessonId"></param>
        /// <param name="returnLessonId">Id of individual Lesson to return to</param>
        /// <returns></returns>
        public ActionResult ToggleMasterEdit(bool isMasterEdit, Guid selectedLessonId, Guid returnLessonId)
        {
            try
            {

CWMT/CWMT/Controllers/WorkingGroupAdminController.cs
using CWMasterTeacher3;
using CWMasterTeacherDataModel.ObjectBuilders;
using CWMasterTeacherDomain.ViewObjects;
using CWMasterTeacherService.CUDRouters;
using CWMasterTeacherService.ViewObjectBuilder;
using CWMT.ReturnModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CWMT.Controllers
{
    public class WorkingGroupAdminController : BaseController
    {
        private WorkingGroupAdminViewObjBuilder _workingGroupViewObjBuilder;
        private WorkingGroupAdminCUDRouter _workingGroupCUDRouter;
        private UserDomainObjBuilder _userObjBuilder;

        public WorkingGroupAdminController(WorkingGroupAdminViewObjBuilder workingGroupViewObjBuilder,
                                            WorkingGroupAdminCUDRouter workingGroupCUDRouter,
                                            UserDomainObjBuilder userObjBuilder) : base(userObjBuilder)
        {
            _workingGroupViewObjBuilder = workingGroupViewObjBuilder;
            _workingGroupCUDRouter = workingGroupCUDRouter;
            _userObjBuilder = userObjBuilder;
        }



        // GET: WorkingGroupAdmin
        public ActionResult Index(Guid? workingGroupId = null, string message = "", bool doShowDeleteWorkingGroup = false)
        {

            WorkingGroupAdminViewObj viewObj = _workingGroupViewObjBuilder.Retrieve(currentUserObj: CurrentUserObj,
                                                            selectedWorkingGroupId: workingGroupId == null ? Guid.Empty : workingGroupId.Value,
                                                            message: message, doShowDeleteWorkingGroup: doShowDeleteWorkingGroup );

            return View(viewObj);
        }


        public ActionResult AddOrUpdateWorkingGroup(WorkingGroupAdminReturnModel model)
        {
            string message = _workingGroupCUDRouter.AddOrUpdateWorkingGroupReturnMessage(workingGroupId: model.WorkingGroupId,
                                                                    name: model.WorkingGroupName, studentAccessCode: model.StudentAccessCode,
                                                                    instructorAccessCode: model.InstructorAccessCode);

            return RedirectToAction("Index", new { workingGroupId = model.WorkingGroupId, message = message });
        }

        public ActionResult DeleteWorkingGroup(CourseCreateAdminReturnModel model)
        {
            try
            {

                string message = _workingGroupCUDRouter.DeleteWorkingGroupReturnMessage(model.WorkingGroupId);
                return RedirectToAction("Index", routeValues: new { message = message, doShowDeleteWorkingGroup = true });
            }
            catch (Exception e)
            {
                WebLogger.Log.DeleteWorkingGroupFailed(e);
                throw;
            }
        }


    }
}

CWMT/CWMT/Views/WorkingGroupAdmin/Index.cshtml
@model CWMasterTeacherDomain.ViewObjects.WorkingGroupAdminViewObj
@{
    Layout = "~/Views/Shared/_LayoutCW2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <!-- Bootstrap core CSS -->
    <link href="Content/bootstrap.css" rel="stylesheet">
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
    <div class=" container-fluid">
        @using (Html.BeginForm("Index", "WorkingGroupAdmin"))
        {
            <div class=" form-horizontal ">
                <div class="form-group">

                    <div class=" row">
                        <div class=" control-label col-md-offset-2 col-md-2">Select WorkingGroup</div>
                        <div class=" col-md-3">
                            @Html.DropDownListFor(m => Model.WorkingGroupId, Model.WorkingGroupSelectList, Model.DropdownDefaultText, htmlAttributes: new { onchange = "this.form.submit();" })
                            @Html.ValidationMessageFor(model => model.WorkingGroupId, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div><!--End Form Group-->
            </div><!--End Form Horizontal-->
            @Html.HiddenFor(m => Model.WorkingGroupId)
        }<!--End Form-->

        @if (Model.WorkingGroupId != Guid.Empty || true)
        {
            using (Html.BeginForm("AddOrUpdateWorkingGroup", "WorkingGroupAdmin"))
            {
                <div class=" form-horizontal ">
                    <div class="form-group">
                        @Html.LabelFor(model => model.WorkingGroupName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 cw-space-above-bigskip">
                            @Html.TextBoxFor(model => model.WorkingGroupName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.WorkingGroupName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.StudentAccessCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 cw-space-above-bigskip">
                            @Html.TextBoxFor(model => model.StudentAccessCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StudentAccessCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.InstructorAccessCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 cw-space-above-bigskip">
                            @Html.TextBoxFor(model => model.InstructorAccessCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.InstructorAccessCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group cw-space-above-bigskip">

                        <div class="col-md-offset-2 col-md-2">
                            @if (Model.WorkingGroupId != Guid.Empty || Model.DoAllowCreate)
                            {
                                <input type="submit" value=@Model.SubmitButtonText class="cw-button-md" />
                            }
                        </div>


                        <span>
                            @Html.ActionLink("Cancel", "Index", "Curriculum", null, new { @class = "cw-button-md" })
                        </span>

                        @Html.HiddenFor(m => Model.WorkingGroupId)
                    </div>

                </div>
            }  <!--End Form-->
        }

        <div class=" row">
            <div class=" cw-red-bold col-md-3 col-md-offset-2 ">
                @Html.DisplayFor(m => Model.Message)
            </div>
        </div>

        @if (Model.WorkingGroupId != Guid.Empty && Model.DoAllowCreate )
        {
            <div class="cw-space-above-bigskip">
                @Html.ActionLink("Delete Working Group", "Index", "WorkingGroupAdmin",
                                routeValues: new { workingGroupId = Model.WorkingGroupId, doShowDeleteWorkingGroup = true },
                                 htmlAttributes: new { @class = "cw-space-above-bigskip cw-underline" })
            </div>
        }



        @if (Model.DoShowDeleteWorkingGroup)
        {
            <div class=" cw-border">
                @using (Html.BeginForm("DeleteWorkingGroup", "WorkingGroupAdmin"))
                {
                    @Html.TextBoxFor(m => Model.WorkingGroupName, htmlAttributes: new { @readonly = "readonly" })
                    <div class=" row cw-space-above-bigskip ">
                        <div class=" col-md-6 ">
                            <div>
                                <input type="submit" value="Confirm Delete WorkingGroup" />
                            </div>
                            <div class=" cw-bold">Careful! This cannot be undone.</div>
                        </div>
                        
                        <div class=" col-md-6 cw-space-above-sm">
                            @Html.ActionLink("Cancel Delete", "Index", "WorkingGroupAdmin",
                                        routeValues: new { },
                                        htmlAttributes: new { @class = "cw-button-md " })
                        </div>
                    </div>
                    @Html.HiddenFor(m => Model.WorkingGroupId)
                }<!--End Form-->
            </div>
        }<!--End if-->






    </div><!--End container fluid-->
</body>
</html>